spring:
  security:
    oauth2:
     resourceserver:
       jwt:
          jwk-set-uri: http://localhost:8080/auth/realms/banque-realm/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
      - id: microservice
        uri: http://localhost:7001/
        predicates:
        - Path=/api/**
server:
  port: 9090

    
